# -*- coding: utf-8 -*-
"""Practica1 EstDescriptiva

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EnvUe6s9P7J7NlBVcWV4zHEUohAEWO7S
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar archivo CSV
df = pd.read_csv("Nacimientos.csv")

# Información básica
print("Información del dataset")
print(df.info())
print("Primeras filas del dataset")
print(df.head())
print("Resumen estadístico del dataset")
print(df.describe())

# Valores faltantes
print("\nValores faltantes por columna:")
print(df.isnull().sum())

# Visualización de nulos
sns.heatmap(df.isnull(), cbar=False, cmap="viridis")
plt.title("Mapa de datos faltantes")
plt.show()

# Valores faltantes
print("\nValores faltantes por columna:")
print(df.isnull().sum())

# Visualización de nulos
sns.heatmap(df.isnull(), cbar=False, cmap="viridis")
plt.title("Mapa de datos faltantes")
plt.show()

df_cleaned = df.dropna()
print("Filas con datos faltantes eliminadas.")
print("Información del dataset después de eliminar valores faltantes:")
print(df_cleaned.info())
print("Primeras filas del dataset después de eliminar valores faltantes:")
print(df_cleaned.head())

# Visualización de nulos después de eliminar filas con NaN
sns.heatmap(df_cleaned.isnull(), cbar=False, cmap="viridis")
plt.title("Mapa de datos faltantes después de eliminar filas con NaN")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Ensure the 'PESO (Gramos)' column is numeric. If it's already converted, this line will not change its type again.
# If it hasn't been converted (e.g., if this cell is run independently), it will convert it.
# This check is important to prevent SettingWithCopyWarning if it was previously converted in a slice.
if df_cleaned['PESO (Gramos)'].dtype == 'object':
    df_cleaned['PESO (Gramos)'] = df_cleaned['PESO (Gramos)'].str.replace(',', '.').astype(float)

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
sns.histplot(df_cleaned['PESO (Gramos)'], kde=True)
plt.title('Distribución de Peso (Gramos)')
plt.xlabel('Peso (Gramos)')
plt.ylabel('Frecuencia')

plt.subplot(1, 2, 2)
sns.histplot(df_cleaned['TALLA (CentImetros)'], kde=True)
plt.title('Distribución de Talla (Centímetros)')
plt.xlabel('Talla (Centímetros)')
plt.ylabel('Frecuencia')

plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
sns.boxplot(y=df_cleaned['PESO (Gramos)'])
plt.title('Diagrama de Caja de Peso (Gramos)')
plt.ylabel('Peso (Gramos)')

plt.subplot(1, 2, 2)
sns.boxplot(y=df_cleaned['TALLA (CentImetros)'])
plt.title('Diagrama de Caja de Talla (Centímetros)')
plt.ylabel('Talla (Centímetros)')

plt.tight_layout()
plt.show()

"""# Task
Remove outliers from the `df_cleaned` DataFrame based on the 'PESO (Gramos)' and 'TALLA (CentImetros)' columns using the IQR method. This involves calculating Q1, Q3, and IQR for each column, then defining lower and upper bounds (Q1 - 1.5 * IQR, Q3 + 1.5 * IQR) to filter out the outliers. Display the shapes of the original `df_cleaned` and the final `df_no_outliers` DataFrames to show the number of rows removed, and display the first few rows of `df_no_outliers`.

## Calculate IQR for 'PESO (Gramos)'

### Subtask:
Calculate the first quartile (Q1), third quartile (Q3), and the Interquartile Range (IQR) for the 'PESO (Gramos)' column in the `df_cleaned` DataFrame.

**Reasoning**:
Calculate the first quartile (Q1), third quartile (Q3), and the Interquartile Range (IQR) for the 'PESO (Gramos)' column in the `df_cleaned` DataFrame.
"""

Q1_peso = df_cleaned['PESO (Gramos)'].quantile(0.25)
Q3_peso = df_cleaned['PESO (Gramos)'].quantile(0.75)
IQR_peso = Q3_peso - Q1_peso

print(f"Primer cuartil (Q1) para PESO (Gramos): {Q1_peso}")
print(f"Tercer cuartil (Q3) para PESO (Gramos): {Q3_peso}")
print(f"Rango intercuartílico (IQR) para PESO (Gramos): {IQR_peso}")

"""**Reasoning**:
Now, calculate the first quartile (Q1), third quartile (Q3), and the Interquartile Range (IQR) for the 'TALLA (CentImetros)' column in the `df_cleaned` DataFrame, similar to how it was done for 'PESO (Gramos)'.


"""

Q1_talla = df_cleaned['TALLA (CentImetros)'].quantile(0.25)
Q3_talla = df_cleaned['TALLA (CentImetros)'].quantile(0.75)
IQR_talla = Q3_talla - Q1_talla

print(f"Primer cuartil (Q1) para TALLA (CentImetros): {Q1_talla}")
print(f"Tercer cuartil (Q3) para TALLA (CentImetros): {Q3_talla}")
print(f"Rango intercuartílico (IQR) para TALLA (CentImetros): {IQR_talla}")

"""**Reasoning**:
Now that Q1, Q3, and IQR have been calculated for both 'PESO (Gramos)' and 'TALLA (CentImetros)', the next logical step is to define the lower and upper bounds for outlier detection using the IQR method (Q1 - 1.5 * IQR and Q3 + 1.5 * IQR) for both columns. This will allow for filtering out outliers in the subsequent step.


"""

lower_bound_peso = Q1_peso - 1.5 * IQR_peso
upper_bound_peso = Q3_peso + 1.5 * IQR_peso

lower_bound_talla = Q1_talla - 1.5 * IQR_talla
upper_bound_talla = Q3_talla + 1.5 * IQR_talla

print(f"Límite inferior para PESO (Gramos): {lower_bound_peso}")
print(f"Límite superior para PESO (Gramos): {upper_bound_peso}")
print(f"Límite inferior para TALLA (CentImetros): {lower_bound_talla}")
print(f"Límite superior para TALLA (CentImetros): {upper_bound_talla}")

"""**Reasoning**:
Now that the lower and upper bounds for outliers have been calculated for both 'PESO (Gramos)' and 'TALLA (CentImetros)', the next step is to filter the `df_cleaned` DataFrame to exclude rows that fall outside these bounds, creating a new DataFrame `df_no_outliers`. This will effectively remove the identified outliers.


"""

df_no_outliers = df_cleaned[
    (df_cleaned['PESO (Gramos)'] >= lower_bound_peso) &
    (df_cleaned['PESO (Gramos)'] <= upper_bound_peso) &
    (df_cleaned['TALLA (CentImetros)'] >= lower_bound_talla) &
    (df_cleaned['TALLA (CentImetros)'] <= upper_bound_talla)
]

print(f"Shape of original df_cleaned: {df_cleaned.shape}")
print(f"Shape of df_no_outliers after removing outliers: {df_no_outliers.shape}")
print("Primeras filas del dataset sin valores atípicos:")
print(df_no_outliers.head())

"""## Summary:

### Data Analysis Key Findings

*   For the 'PESO (Gramos)' column, the first quartile (Q1) was 2.67, the third quartile (Q3) was 3.33, and the Interquartile Range (IQR) was 0.66.
*   Based on the IQR method, the lower bound for 'PESO (Gramos)' outliers was approximately 1.68, and the upper bound was 4.32.
*   For the 'TALLA (CentImetros)' column, the first quartile (Q1) was 46.0, the third quartile (Q3) was 50.0, and the Interquartile Range (IQR) was 4.0.
*   Based on the IQR method, the lower bound for 'TALLA (CentImetros)' outliers was 40.0, and the upper bound was 56.0.
*   The original `df_cleaned` DataFrame contained 8837 rows and 32 columns.
*   After removing outliers, the `df_no_outliers` DataFrame contains 8572 rows and 32 columns, indicating that 265 rows were identified and removed as outliers.

### Insights or Next Steps

*   The dataset `df_no_outliers` is now robust against extreme values in 'PESO (Gramos)' and 'TALLA (CentImetros)', making it more suitable for statistical analysis or machine learning models that are sensitive to outliers.
*   Consider visualizing the distribution of the removed outliers (e.g., their counts per category or other features) to understand if they represent data errors, rare events, or specific subgroups that might warrant separate analysis rather than outright removal.

"""

import matplotlib.pyplot as plt
import seaborn as sns

# Histograms for 'PESO (Gramos)' and 'TALLA (CentImetros)' after outlier removal
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
sns.histplot(df_no_outliers['PESO (Gramos)'], kde=True)
plt.title('Distribución de Peso (Gramos) sin Outliers')
plt.xlabel('Peso (Gramos)')
plt.ylabel('Frecuencia')

plt.subplot(1, 2, 2)
sns.histplot(df_no_outliers['TALLA (CentImetros)'], kde=True)
plt.title('Distribución de Talla (Centímetros) sin Outliers')
plt.xlabel('Talla (Centímetros)')
plt.ylabel('Frecuencia')

plt.tight_layout()
plt.show()

# Box plots for 'PESO (Gramos)' and 'TALLA (CentImetros)' after outlier removal
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
sns.boxplot(y=df_no_outliers['PESO (Gramos)'])
plt.title('Diagrama de Caja de Peso (Gramos) sin Outliers')
plt.ylabel('Peso (Gramos)')

plt.subplot(1, 2, 2)
sns.boxplot(y=df_no_outliers['TALLA (CentImetros)'])
plt.title('Diagrama de Caja de Talla (Centímetros) sin Outliers')
plt.ylabel('Talla (Centímetros)')

plt.tight_layout()
plt.show()

plt.figure(figsize=(18, 6))

# Pie chart for SEXO
plt.subplot(1, 3, 1)
df_no_outliers['SEXO'].value_counts().plot.pie(autopct='%1.1f%%', startangle=90, wedgeprops={'edgecolor': 'black'})
plt.title('Distribución de Sexo')
plt.ylabel('') # Remove y-label for better aesthetics

# Pie chart for TIPO PARTO
plt.subplot(1, 3, 2)
df_no_outliers['TIPO PARTO'].value_counts().plot.pie(autopct='%1.1f%%', startangle=90, wedgeprops={'edgecolor': 'black'})
plt.title('Distribución de Tipo de Parto')
plt.ylabel('')

# Pie chart for PERTENENCIA ETNICA
plt.subplot(1, 3, 3)
df_no_outliers['PERTENENCIA ETNICA'].value_counts().plot.pie(autopct='%1.1f%%', startangle=90, wedgeprops={'edgecolor': 'black'})
plt.title('Distribución de Pertenencia Étnica')
plt.ylabel('')

plt.tight_layout()
plt.show()

from scipy import stats
import statsmodels.api as sm
import matplotlib.pyplot as plt

# --- Análisis de normalidad para 'PESO (Gramos)' ---
print("\n--- Análisis de normalidad para PESO (Gramos) ---")

# Shapiro-Wilk Test
stat, p = stats.shapiro(df_no_outliers['PESO (Gramos)'])
print('Shapiro-Wilk Test: Statistics=%.3f, p=%.3f' % (stat, p))
if p > 0.05:
    print('Parece normal (No se rechaza H0)')
else:
    print('No parece normal (Se rechaza H0)')

# Kolmogorov-Smirnov Test
# For K-S test, we need to provide the parameters of the normal distribution (mean, std dev)
mean_peso = df_no_outliers['PESO (Gramos)'].mean()
std_peso = df_no_outliers['PESO (Gramos)'].std()
stat, p = stats.kstest(df_no_outliers['PESO (Gramos)'], 'norm', args=(mean_peso, std_peso))
print('Kolmogorov-Smirnov Test: Statistics=%.3f, p=%.3f' % (stat, p))
if p > 0.05:
    print('Parece normal (No se rechaza H0)')
else:
    print('No parece normal (Se rechaza H0)')

# Anderson-Darling Test
result = stats.anderson(df_no_outliers['PESO (Gramos)'], dist='norm')
print('Anderson-Darling Test: Statistics=%.3f' % result.statistic)
for i in range(len(result.critical_values)):
    sl, cv = result.significance_level[i], result.critical_values[i]
    if result.statistic < cv:
        print('  Parece normal en el nivel de significancia del %.1f%% (crítico=%.3f)' % (sl, cv))
    else:
        print('  No parece normal en el nivel de significancia del %.1f%% (crítico=%.3f)' % (sl, cv))

# QQ-plot para PESO (Gramos)
sm.qqplot(df_no_outliers['PESO (Gramos)'], line='s')
plt.title('QQ-plot para PESO (Gramos)')
plt.show()

# --- Análisis de normalidad para 'TALLA (CentImetros)' ---
print("\n--- Análisis de normalidad para TALLA (CentImetros) ---")

# Shapiro-Wilk Test
stat, p = stats.shapiro(df_no_outliers['TALLA (CentImetros)'])
print('Shapiro-Wilk Test: Statistics=%.3f, p=%.3f' % (stat, p))
if p > 0.05:
    print('Parece normal (No se rechaza H0)')
else:
    print('No parece normal (Se rechaza H0)')

# Kolmogorov-Smirnov Test
mean_talla = df_no_outliers['TALLA (CentImetros)'].mean()
std_talla = df_no_outliers['TALLA (CentImetros)'].std()
stat, p = stats.kstest(df_no_outliers['TALLA (CentImetros)'], 'norm', args=(mean_talla, std_talla))
print('Kolmogorov-Smirnov Test: Statistics=%.3f, p=%.3f' % (stat, p))
if p > 0.05:
    print('Parece normal (No se rechaza H0)')
else:
    print('No parece normal (Se rechaza H0)')

# Anderson-Darling Test
result = stats.anderson(df_no_outliers['TALLA (CentImetros)'], dist='norm')
print('Anderson-Darling Test: Statistics=%.3f' % result.statistic)
for i in range(len(result.critical_values)):
    sl, cv = result.significance_level[i], result.critical_values[i]
    if result.statistic < cv:
        print('  Parece normal en el nivel de significancia del %.1f%% (crítico=%.3f)' % (sl, cv))
    else:
        print('  No parece normal en el nivel de significancia del %.1f%% (crítico=%.3f)' % (sl, cv))

# QQ-plot para TALLA (CentImetros)
sm.qqplot(df_no_outliers['TALLA (CentImetros)'], line='s')
plt.title('QQ-plot para TALLA (CentImetros)')
plt.show()

"""He analizado los resultados del test de normalidad para las variables de 'PESO (Gramos)' y 'TALLA (CentImetros)'.

Para ambas variables, los tests de Shapiro-Wilk, Kolmogorov-Smirnov y Anderson-Darling indican que los datos no parecen seguir una distribución normal, ya que los valores p son muy bajos (0.000), rechazando la hipótesis nula de normalidad en todos los casos.

Los gráficos QQ-plot también visualizan esta desviación de la normalidad, mostrando que los puntos no se alinean perfectamente con la línea teórica de una distribución normal. Aunque se eliminaron los outliers, la distribución subyacente de estas variables no es normal.
"""

